### ISSUE TITLE
preprocessor bug report 

### ISSUE THREAD

**Issue by nkmtmsys** [JackSSK/FateZ#1]
sudo python3 test_gat_10x_paired.py

scanpy==1.9.1 anndata==0.8.0 umap==0.5.3 numpy==1.19.5 scipy==1.8.0 pandas==1.4.2 scikit-learn==1.0.2 statsmodels==0.13.5 pynndescent==0.5.7

Traceback (most recent call last):
  File "test_gat_10x_paired.py", line 27, in <module>
    network.load_data()
  File "/usr/local/lib/python3.8/dist-packages/fatez/process/preprocessor.py", line 161, in load_data
    self.peak_region_df = pd.DataFrame({'chr':chr_list,'start':start_list,'end':end_list},index=peak_names)
UnboundLocalError: local variable 'chr_list' referenced before assignment

**Comment by JackSSK** [comment]
Fixed
